const THEMES = {
  fast: {label:'Sell Fast',angle:'Speed and flexible closing',headline:'Need to Sell Your House Fast in {city}?',subheadline:'Request a simple cash offer and choose a closing date that works for you.',cta:'Get My Fast Cash Offer',chat:'Hi, I can help you request a fast cash offer. How soon are you hoping to sell?',faq:'No. You can review the offer and decide if it makes sense.'},
  repairs: {label:'Repairs / As-Is',angle:'No repairs or cleanup',headline:'Sell Your House As-Is in {city}',subheadline:'No repairs, updates, painting, or cleanup required before requesting an offer.',cta:'Get an As-Is Offer',chat:'Hi, I can help with an as-is offer. What repairs does the property need?',faq:'Yes. The point of an as-is offer is to review the property without asking you to repair it first.'},
  inherited: {label:'Inherited House',angle:'Inherited property help',headline:'Inherited a House in {city}?',subheadline:'Request an offer without cleaning it out, making repairs, or listing it with an agent.',cta:'Get an Inherited House Offer',chat:'Hi, I can help with an inherited property. Is the house currently occupied or vacant?',faq:'Often, yes. The buyer can review the property condition and situation.'},
  foreclosure: {label:'Foreclosure Concern',angle:'Timeline and options',headline:'Need to Sell a House Quickly in {city}?',subheadline:'Request a cash offer and review whether selling may be an option for your timeline.',cta:'Talk Through My Options',chat:'Hi, I can help you request an offer and review your timeline. Are you looking to sell quickly?',faq:'There are no guarantees. A cash offer may be one option to review depending on your timeline and situation.'},
  landlord: {label:'Tired Landlord',angle:'Rental property exit',headline:'Ready to Sell Your Rental Property in {city}?',subheadline:'Request a cash offer whether the property is vacant, occupied, outdated, or needs repairs.',cta:'Get a Rental Property Offer',chat:'Hi, I can help with a rental property offer. Is the property currently occupied?',faq:'Many buyers will review occupied rental properties. Details matter.'}
};
const MOCK_PERFORMANCE = [
  {theme:'Repairs / As-Is',clicks:238,leads:31,conversion:'13.0%',cpl:'$72'},
  {theme:'Inherited House',clicks:176,leads:22,conversion:'12.5%',cpl:'$81'},
  {theme:'Sell Fast',clicks:294,leads:26,conversion:'8.8%',cpl:'$96'},
  {theme:'Tired Landlord',clicks:112,leads:11,conversion:'9.8%',cpl:'$88'},
  {theme:'Foreclosure Concern',clicks:188,leads:12,conversion:'6.4%',cpl:'$124'}
];
const MOCK_LEADS = [
  {name:'Demo Lead 1',phone:'(555) 201-1001',city:'Plano',theme:'Repairs / As-Is',status:'New'},
  {name:'Demo Lead 2',phone:'(555) 201-1002',city:'Frisco',theme:'Inherited House',status:'Contacted'},
  {name:'Demo Lead 3',phone:'(555) 201-1003',city:'Dallas',theme:'Sell Fast',status:'Reviewing'},
  {name:'Demo Lead 4',phone:'(555) 201-1004',city:'McKinney',theme:'Foreclosure Concern',status:'New'}
];
function getStoredLeads(){try{return JSON.parse(localStorage.getItem('demoLeads')||'[]')}catch{return[]}}
function getStoredVisits(){try{return JSON.parse(localStorage.getItem('demoVisits')||'[]')}catch{return[]}}
function adminLayout(active,title,subtitle,content){document.body.innerHTML=`<div class="admin-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">DL</div><div><strong>DynLander</strong><br><small>Admin demo</small></div></div><nav class="nav"><a class="${active==='dashboard'?'active':''}" href="/admin/">Dashboard</a><a class="${active==='themes'?'active':''}" href="/admin/themes/">Theme Editor</a><a class="${active==='url'?'active':''}" href="/admin/url-builder/">URL Builder</a><a class="${active==='leads'?'active':''}" href="/admin/leads/">Leads</a><a href="/?theme=repairs&city=Plano&utm_source=google&utm_medium=cpc&utm_campaign=as-is-repairs">View Landing Page</a></nav></aside><main class="main"><div class="top"><div><h1>${title}</h1><p>${subtitle}</p></div><a class="button" href="/admin/url-builder/">Build Ad URL</a></div>${content}</main></div>`}
function renderDashboard(){const visits=getStoredVisits();const stored=getStoredLeads();const totalClicks=MOCK_PERFORMANCE.reduce((s,r)=>s+r.clicks,0)+visits.length;const totalLeads=MOCK_PERFORMANCE.reduce((s,r)=>s+r.leads,0)+stored.length;const rate=((totalLeads/totalClicks)*100).toFixed(1);const rows=MOCK_PERFORMANCE.map(r=>`<tr><td>${r.theme}</td><td>${r.clicks}</td><td>${r.leads}</td><td>${r.conversion}</td><td>${r.cpl}</td></tr>`).join('');const leads=[...stored.map(l=>({name:l.name,phone:l.phone,city:l.property_city||l.city,theme:THEMES[l.theme]?.label||l.theme,status:'Demo captured'})),...MOCK_LEADS];adminLayout('dashboard','DynLander Admin','Manage dynamic landing pages, seller-intent themes, Google Ads URLs, and home-buyer lead reporting. This static demo works on your current repo.',`<section class="grid"><div class="card metric"><span>Total clicks</span><strong>${totalClicks}</strong></div><div class="card metric"><span>Total leads</span><strong>${totalLeads}</strong></div><div class="card metric"><span>Conversion rate</span><strong>${rate}%</strong></div><div class="card metric"><span>Best theme</span><strong>Repairs</strong></div></section><section class="card"><h2>Theme performance</h2><table><thead><tr><th>Theme</th><th>Clicks</th><th>Leads</th><th>Conversion</th><th>Demo CPL</th></tr></thead><tbody>${rows}</tbody></table></section><section class="card"><h2>AI-style recommendations</h2><div class="grid"><div class="recommendation"><strong>Scale repairs theme</strong><span class="muted">Repairs / as-is has the highest lead count and should get more budget or more ad variants.</span></div><div class="recommendation"><strong>Review foreclosure copy</strong><span class="muted">Foreclosure clicks are strong, but conversion is weaker. Test softer language and more trust-building content.</span></div><div class="recommendation"><strong>Create city variants</strong><span class="muted">Dallas and Plano are driving strong demo leads. Build local proof sections next.</span></div></div></section><section class="card"><h2>Recent leads</h2><table><thead><tr><th>Name</th><th>Phone</th><th>City</th><th>Theme</th><th>Status</th></tr></thead><tbody>${leads.slice(0,8).map(l=>`<tr><td>${l.name||''}</td><td>${l.phone||''}</td><td>${l.city||''}</td><td>${l.theme||''}</td><td>${l.status||''}</td></tr>`).join('')}</tbody></table></section>`)}
function renderThemes(){const cards=Object.entries(THEMES).map(([id,t])=>`<section class="card"><div style="display:flex;justify-content:space-between;gap:12px"><h2 style="margin-top:0">${t.label}</h2><span class="pill">${id}</span></div><div class="two"><label>Headline<input value="${t.headline.replaceAll('"','&quot;')}"></label><label>CTA<input value="${t.cta.replaceAll('"','&quot;')}"></label></div><label>Subheadline<textarea>${t.subheadline}</textarea></label><label>Chat opening<textarea>${t.chat}</textarea></label><label>FAQ answer<textarea>${t.faq}</textarea></label><p class="muted">Demo only: edits are visual only. Production would save this to a database.</p></section>`).join('');adminLayout('themes','Theme Editor','Review the seller-intent themes that control the dynamic landing page copy.',cards)}
function renderUrlBuilder(){adminLayout('url','Google Ads URL Builder','Create final URLs that pass seller intent, city, campaign, keyword, device, and match type into the landing page.',`<section class="card"><div class="two"><label>Theme<select id="theme">${Object.entries(THEMES).map(([id,t])=>`<option value="${id}">${t.label}</option>`).join('')}</select></label><label>City<input id="city" value="Plano"></label><label>Campaign<input id="campaign" value="as-is-repairs"></label><label>Keyword<input id="keyword" value="sell house as is"></label><label>Device<select id="device"><option value="{device}">Use Google {device}</option><option value="m">Mobile</option><option value="c">Computer</option><option value="t">Tablet</option></select></label><label>Match type<select id="matchtype"><option value="{matchtype}">Use Google {matchtype}</option><option value="e">Exact</option><option value="p">Phrase</option><option value="b">Broad</option></select></label></div><button class="button" id="build">Build URL</button></section><section class="card"><h2>Final URL</h2><div class="code" id="output">Click Build URL</div><p><a class="button secondary" id="testLink" href="/">Open test URL</a></p></section>`);const build=()=>{const theme=document.getElementById('theme').value;const city=encodeURIComponent(document.getElementById('city').value||'Plano');const campaign=encodeURIComponent(document.getElementById('campaign').value||'demo');const keyword=encodeURIComponent(document.getElementById('keyword').value||'not-set');const device=encodeURIComponent(document.getElementById('device').value);const matchtype=encodeURIComponent(document.getElementById('matchtype').value);const url=`${location.origin}/?theme=${theme}&city=${city}&utm_source=google&utm_medium=cpc&utm_campaign=${campaign}&keyword=${keyword}&device=${device}&matchtype=${matchtype}`;document.getElementById('output').textContent=url;document.getElementById('testLink').href=url};document.getElementById('build').addEventListener('click',build);build()}
function renderLeads(){const stored=getStoredLeads().map(l=>({date:l.date?new Date(l.date).toLocaleString():'',name:l.name,phone:l.phone,city:l.property_city||l.city,theme:THEMES[l.theme]?.label||l.theme,campaign:l.campaign||'',source:l.source||'google'}));const rows=[...stored,...MOCK_LEADS.map(l=>({...l,date:'Mock',campaign:'demo',source:'google'}))].map(l=>`<tr><td>${l.date||''}</td><td>${l.name||''}</td><td>${l.phone||''}</td><td>${l.city||''}</td><td>${l.theme||''}</td><td>${l.campaign||''}</td><td>${l.source||''}</td></tr>`).join('');adminLayout('leads','Lead Dashboard','Review leads captured from the demo landing page and see which theme/city/campaign created them.',`<section class="card"><table><thead><tr><th>Date</th><th>Name</th><th>Phone</th><th>City</th><th>Theme</th><th>Campaign</th><th>Source</th></tr></thead><tbody>${rows}</tbody></table></section>`)}
function route(){const p=location.pathname.replace(/\/$/,'');if(p.endsWith('/admin/themes'))return renderThemes();if(p.endsWith('/admin/url-builder'))return renderUrlBuilder();if(p.endsWith('/admin/leads'))return renderLeads();return renderDashboard()}route();
